# Generated by Django 6.0.3 on 2026-03-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='file',
            name='volume',
        ),
    ]
