# Generated by Django 6.0.2 on 2026-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_file_comment_remove_file_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='case_brief',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='file',
            name='date_invited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
